<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository {

    public function getJobListApi($filters, $orderBy, $count, $page) {

        $qb = $this->createQueryBuilder('job');

        foreach ($filters as $name => $data) {

            $filterDataName = 'filterData' . $name;
            $filterDataNameParam = ':filterData' . $name;

            $qb->andWhere($qb->expr()->like('job.' . $name, $filterDataNameParam));
            $qb->setParameter($filterDataName, '%' . $data . '%');
        }
        
        $qb->setFirstResult($page * $count);
        $qb->setMaxResults($count);

        return $qb->getQuery()->getArrayResult();
    }

}
