app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
ever_job_api:
    type: rest
    prefix: /api
    resource: "@AppBundle/Api/Resources/config/routing_api.yml"
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc